# Generated by Django 5.2.5 on 2025-08-22 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="manager",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.branch",
            ),
        ),
    ]
